name: Build CI

on:
  push:
  pull_request:
  schedule:
    # build the main branch every Monday morning
    - cron: '17 5 * * 1'
  workflow_dispatch:

jobs:
  build-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [cc, clang, clang-12, gcc-10]
    steps:
      - uses: actions/checkout@v3
      - name: autogen
        run: ./autogen.sh
      - name: compiler
        run: $CC -v
        env:
          CC: ${{ matrix.compiler }}
      - name: install missing deps
        run: sudo apt-get install libtls-dev
      - name: configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: make
        run: make -k
      - name: make distcheck
        run: make distcheck
        if: matrix.compiler == 'cc'
      - name: test run rrdp
        run: mkdir rpki-cache rpki; src/rpki-client -v -t afrinic.tal -t apnic.tal -t lacnic.tal -t ripe.tal -d rpki-cache rpki
        if: matrix.compiler == 'cc'
      - name: test run rsync
        run: mkdir rpki-cache-rrdp rpki-rrdp; src/rpki-client -vR -t afrinic.tal -t apnic.tal -t lacnic.tal -t ripe.tal -d rpki-cache-rrdp rpki-rrdp
        if: matrix.compiler == 'clang'
